### ISSUE TITLE
Please consider supporting os-client-config style clouds.yml files

### ISSUE THREAD

**Issue by JonTheNiceGuy** [ggiamarchi/vagrant-openstack-provider#350]
Hi!

I'm about to start using this provider, but I was wondering whether it would be possible for you to consider using the os-client-config style files. These files are typically (on Linux at least) stored in ./clouds.y(a)ml, $HOME/.config/openstack/clouds.y(a)ml and /etc/openstack/clouds.y(a)ml. OS X and Windows have their own paths.

The format of these files is documented in https://docs.openstack.org/os-client-config/latest/user/configuration.html

The python library to load these files is here: https://github.com/openstack/os-client-config

Here's an example file (from the docs url above):

```
clouds:
  mtvexx:
    profile: vexxhost
    auth:
      username: mordred@inaugust.com
      password: XXXXXXXXX
      project_name: mordred@inaugust.com
    region_name: ca-ymq-1
    dns_api_version: 1

  mordred:
    region_name: RegionOne
    auth:
      username: 'mordred'
      password: XXXXXXX
      project_name: 'shade'
      auth_url: 'https://montytaylor-sjc.openstack.blueboxgrid.com:5001/v2.0'

  infra:
    profile: rackspace
    auth:
      username: openstackci
      password: XXXXXXXX
      project_id: 610275
    regions:
    - DFW
    - ORD
    - IAD
```
