### ISSUE TITLE
How to configure dns zone ?

### ISSUE THREAD

**Issue by devnewton** [ggiamarchi/vagrant-openstack-provider#380]
I would like to configure dns zone using Heat stacks or Vagrantfile. I cannot figure the way to do it.

**Comment by ggiamarchi** [comment]
Here is an example [using a Heat stack](https://github.com/ggiamarchi/vagrant-openstack-provider/tree/master/samples/04_heat_stack). In this example, the Heat stack creates the needed network infrastructure into the project in order to be able to spawn an instance (i.e. router, network, subnet...).

I'm closing the issue but feel free to comment here again if you have any question.

**Comment by devnewton** [comment]
If I want to add dns zone configuration to the heat stack in your example, how can I get the server address?

```
record:
   type: OS::Designate::RecordSet
   properties:
      zone: "myzone.com."
      records:  [ ???How to get a server address here??? ]
      name: { ???How to get a server name here??? }
      type: "A"
```
